-- ==============================================================================
-- SCRIPT MAESTRO DE BASE DE DATOS SACPA
-- Sistema de Alertas de Caducidad de Productos Agricolas
-- Base de datos: BD_sistema_agro | PostgreSQL 16
-- Ejecutar como superusuario (postgres)
-- ==============================================================================

-- ==============================================================================
-- FASE 0: LIMPIEZA Y CREACION DE ESQUEMAS
-- ==============================================================================

-- Eliminar esquemas antiguos si existieran (solo public sin tablas propias)
-- DROP SCHEMA IF EXISTS public CASCADE;
-- CREATE SCHEMA public;

-- Crear esquemas del sistema
CREATE SCHEMA IF NOT EXISTS catalogos;
CREATE SCHEMA IF NOT EXISTS geografia;
CREATE SCHEMA IF NOT EXISTS entidades;
CREATE SCHEMA IF NOT EXISTS seguridad;
CREATE SCHEMA IF NOT EXISTS inventario;
CREATE SCHEMA IF NOT EXISTS operaciones;
CREATE SCHEMA IF NOT EXISTS ia_alertas;
CREATE SCHEMA IF NOT EXISTS gerencia;

-- ==============================================================================
-- FASE 1: MODELO DE DATOS (DDL - Creacion de Tablas)
-- ==============================================================================

-- --------------------------------------------------------------------------
-- 1.1 Esquema: CATALOGOS
-- --------------------------------------------------------------------------

CREATE TABLE catalogos.cat_estado_general (
    id_estado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE catalogos.cat_estado_lote (
    id_estado_lote INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE catalogos.cat_tipo_movimiento (
    id_tipo_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    naturaleza VARCHAR(50),
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE catalogos.cat_nivel_alerta (
    id_nivel_alerta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE catalogos.cat_estado_aprobacion (
    id_estado_aprobacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN DEFAULT TRUE
);

-- --------------------------------------------------------------------------
-- 1.2 Esquema: GEOGRAFIA
-- --------------------------------------------------------------------------

CREATE TABLE geografia.pais (
    id_pais INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    codigo_iso VARCHAR(10)
);

CREATE TABLE geografia.provincia (
    id_provincia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    id_pais INTEGER NOT NULL REFERENCES geografia.pais(id_pais)
);

CREATE TABLE geografia.ciudad (
    id_ciudad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    id_provincia INTEGER NOT NULL REFERENCES geografia.provincia(id_provincia)
);

-- --------------------------------------------------------------------------
-- 1.3 Esquema: SEGURIDAD
-- --------------------------------------------------------------------------

CREATE TABLE seguridad.rol_bd (
    id_rol_bd INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol_bd VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE seguridad.rol (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    id_estado INTEGER,
    id_rol_bd INTEGER REFERENCES seguridad.rol_bd(id_rol_bd)
);

CREATE TABLE seguridad.usuario (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(150) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    id_estado INTEGER NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP
);

CREATE TABLE seguridad.usuario_rol (
    id_usuario_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario) ON DELETE CASCADE,
    id_rol INTEGER NOT NULL REFERENCES seguridad.rol(id_rol)
);

CREATE TABLE seguridad.tipo_objeto_seguridad (
    id_tipo_objeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE seguridad.privilegio (
    id_privilegio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    accion VARCHAR(100),
    activo BOOLEAN DEFAULT TRUE,
    id_tipo_objeto INTEGER REFERENCES seguridad.tipo_objeto_seguridad(id_tipo_objeto),
    esquema VARCHAR(100),
    nombre_tabla VARCHAR(100)
);

CREATE TABLE seguridad.rol_privilegio (
    id_rol_privilegio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL REFERENCES seguridad.rol(id_rol) ON DELETE CASCADE,
    id_privilegio INTEGER NOT NULL REFERENCES seguridad.privilegio(id_privilegio) ON DELETE CASCADE
);

CREATE TABLE seguridad.historial_sesion (
    id_sesion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_acceso VARCHAR(50),
    fecha_ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_salida TIMESTAMP,
    rol_utilizado VARCHAR(100),
    id_usuario INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE seguridad.auditoria (
    id_auditoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla_afectada VARCHAR(100),
    operacion VARCHAR(50),
    descripcion TEXT,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_usuario INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE seguridad.solicitud_registro (
    id_solicitud INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(150) NOT NULL,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    cedula VARCHAR(20) NOT NULL,
    telefono VARCHAR(30),
    departamento VARCHAR(100),
    cargo VARCHAR(100),
    fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado INTEGER DEFAULT 1,
    motivo_rechazo TEXT,
    procesado_por INTEGER REFERENCES seguridad.usuario(id_usuario),
    fecha_procesamiento TIMESTAMP
);

-- --------------------------------------------------------------------------
-- 1.4 Esquema: ENTIDADES
-- --------------------------------------------------------------------------

CREATE TABLE entidades.empresa (
    id_empresa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    ruc VARCHAR(20),
    direccion VARCHAR(300),
    telefono VARCHAR(30),
    correo VARCHAR(150)
);

CREATE TABLE entidades.proveedor (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    ruc VARCHAR(20),
    telefono VARCHAR(30),
    direccion VARCHAR(300),
    id_estado INTEGER,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

-- --------------------------------------------------------------------------
-- 1.5 Esquema: GERENCIA
-- --------------------------------------------------------------------------

CREATE TABLE gerencia.administrador (
    id_administrador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20),
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    telefono VARCHAR(30),
    foto_perfil TEXT,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE gerencia.empleado (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20) NOT NULL UNIQUE,
    nombres VARCHAR(150) NOT NULL,
    apellidos VARCHAR(150) NOT NULL,
    telefono VARCHAR(30),
    departamento VARCHAR(100),
    cargo VARCHAR(100),
    fecha_ingreso DATE DEFAULT CURRENT_DATE,
    foto_perfil TEXT,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario) ON DELETE SET NULL,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE gerencia.gerente (
    id_gerente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20),
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    telefono VARCHAR(30),
    departamento VARCHAR(100),
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

-- --------------------------------------------------------------------------
-- 1.6 Esquema: INVENTARIO
-- --------------------------------------------------------------------------

CREATE TABLE inventario.categoria (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    id_estado INTEGER
);

CREATE TABLE inventario.producto (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    descripcion TEXT,
    unidad_medida VARCHAR(50),
    precio DECIMAL(10,2),
    id_estado INTEGER,
    id_categoria INTEGER NOT NULL REFERENCES inventario.categoria(id_categoria)
);

CREATE TABLE inventario.registro_sanitario (
    id_registro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_registro VARCHAR(100),
    organismo_emisor VARCHAR(200),
    fecha_emision DATE,
    fecha_vigencia DATE,
    id_estado INTEGER,
    id_producto INTEGER NOT NULL REFERENCES inventario.producto(id_producto)
);

CREATE TABLE inventario.almacen (
    id_almacen INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(200) NOT NULL,
    capacidad_total DECIMAL(12,2),
    id_estado INTEGER,
    id_ciudad INTEGER NOT NULL REFERENCES geografia.ciudad(id_ciudad)
);

CREATE TABLE inventario.zona_almacen (
    id_zona INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    condicion_climatica VARCHAR(100),
    id_estado INTEGER,
    id_almacen INTEGER NOT NULL REFERENCES inventario.almacen(id_almacen)
);

CREATE TABLE inventario.estanteria (
    id_estanteria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    id_estado INTEGER,
    id_zona INTEGER NOT NULL REFERENCES inventario.zona_almacen(id_zona)
);

CREATE TABLE inventario.ubicacion_interna (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel VARCHAR(50),
    posicion VARCHAR(50),
    id_estado INTEGER,
    id_estanteria INTEGER NOT NULL REFERENCES inventario.estanteria(id_estanteria)
);

CREATE TABLE inventario.lotes (
    id_lote INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_lote VARCHAR(100) NOT NULL UNIQUE,
    fecha_fabricacion DATE,
    fecha_vencimiento DATE NOT NULL,
    cantidad_inicial INTEGER,
    cantidad_actual INTEGER,
    fecha_ingreso TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado_lote INTEGER,
    id_producto INTEGER NOT NULL REFERENCES inventario.producto(id_producto),
    id_proveedor INTEGER NOT NULL REFERENCES entidades.proveedor(id_proveedor),
    id_ubicacion INTEGER NOT NULL REFERENCES inventario.ubicacion_interna(id_ubicacion)
);

CREATE TABLE inventario.documentos_lote (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_archivo VARCHAR(200),
    ruta_archivo VARCHAR(500),
    tipo_documento VARCHAR(100),
    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote)
);

CREATE TABLE inventario.historial_estado_lote (
    id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estado_anterior INTEGER,
    id_estado_nuevo INTEGER,
    observacion TEXT,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_usuario INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE inventario.bodeguero (
    id_bodeguero INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20),
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    telefono VARCHAR(30),
    turno VARCHAR(50),
    id_estado INTEGER,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE inventario.supervisor (
    id_supervisor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20),
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    telefono VARCHAR(30),
    area_supervision VARCHAR(150),
    id_estado INTEGER,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

-- --------------------------------------------------------------------------
-- 1.7 Esquema: OPERACIONES
-- --------------------------------------------------------------------------

CREATE TABLE operaciones.movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad INTEGER,
    observacion TEXT,
    fecha_movimiento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado_aprobacion INTEGER,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_tipo_movimiento INTEGER NOT NULL REFERENCES catalogos.cat_tipo_movimiento(id_tipo_movimiento),
    id_usuario INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE operaciones.devoluciones (
    id_devolucion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    motivo TEXT,
    cantidad INTEGER,
    fecha_devolucion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado_aprobacion INTEGER,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_proveedor INTEGER NOT NULL REFERENCES entidades.proveedor(id_proveedor),
    id_usuario_supervisor INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE operaciones.uso_campo (
    id_uso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcela VARCHAR(150),
    cultivo VARCHAR(150),
    fecha_aplicacion DATE,
    cantidad_usada INTEGER,
    observacion TEXT,
    id_estado INTEGER,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_usuario_tecnico INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE operaciones.tecnico_campo (
    id_tecnico INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cedula VARCHAR(20) UNIQUE,
    nombres VARCHAR(150),
    apellidos VARCHAR(150),
    telefono VARCHAR(30),
    licencia_agricola VARCHAR(100),
    id_estado INTEGER,
    id_usuario INTEGER REFERENCES seguridad.usuario(id_usuario)
);

-- --------------------------------------------------------------------------
-- 1.8 Esquema: IA_ALERTAS
-- --------------------------------------------------------------------------

CREATE TABLE ia_alertas.modelo_ia (
    id_modelo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_modelo VARCHAR(200) NOT NULL,
    version VARCHAR(50),
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE
);

CREATE TABLE ia_alertas.ejecucion_ia (
    id_ejecucion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parametros_enviados TEXT,
    fecha_ejecucion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado INTEGER,
    id_modelo INTEGER NOT NULL REFERENCES ia_alertas.modelo_ia(id_modelo)
);

CREATE TABLE ia_alertas.temporadas_agricolas (
    id_temporada INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_temporada VARCHAR(150) NOT NULL,
    cultivo VARCHAR(150),
    fecha_inicio DATE,
    fecha_fin DATE,
    id_estado INTEGER
);

CREATE TABLE ia_alertas.alertas_caducidad (
    id_alerta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensaje TEXT,
    fecha_generacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_estado INTEGER,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_nivel_alerta INTEGER NOT NULL REFERENCES catalogos.cat_nivel_alerta(id_nivel_alerta)
);

CREATE TABLE ia_alertas.configuracion_alertas (
    id_configuracion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dias_anticipacion INTEGER,
    activo BOOLEAN DEFAULT TRUE,
    id_nivel_alerta INTEGER NOT NULL REFERENCES catalogos.cat_nivel_alerta(id_nivel_alerta),
    id_usuario_modificador INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE ia_alertas.notificacion (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal VARCHAR(50),
    fecha_envio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    leida BOOLEAN DEFAULT FALSE,
    fecha_lectura TIMESTAMP,
    id_alerta INTEGER NOT NULL REFERENCES ia_alertas.alertas_caducidad(id_alerta),
    id_usuario_destino INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE ia_alertas.sugerencias_ia (
    id_sugerencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    porcentaje_descuento DECIMAL(5,2),
    observaciones TEXT,
    fecha_sugerencia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id_lote INTEGER NOT NULL REFERENCES inventario.lotes(id_lote),
    id_temporada INTEGER NOT NULL REFERENCES ia_alertas.temporadas_agricolas(id_temporada),
    id_ejecucion INTEGER NOT NULL REFERENCES ia_alertas.ejecucion_ia(id_ejecucion),
    id_estado_aprobacion INTEGER NOT NULL REFERENCES catalogos.cat_estado_aprobacion(id_estado_aprobacion)
);

CREATE TABLE ia_alertas.promociones (
    id_promocion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_promocion VARCHAR(200) NOT NULL,
    descripcion TEXT,
    descuento_global DECIMAL(5,2),
    fecha_inicio DATE,
    fecha_fin DATE,
    id_estado INTEGER,
    id_sugerencia INTEGER REFERENCES ia_alertas.sugerencias_ia(id_sugerencia),
    id_usuario_aprueba INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario)
);

CREATE TABLE ia_alertas.promocion_detalle (
    id_detalle INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad_requerida INTEGER DEFAULT 1,
    id_promocion INTEGER NOT NULL REFERENCES ia_alertas.promociones(id_promocion),
    id_producto INTEGER NOT NULL REFERENCES inventario.producto(id_producto)
);

CREATE TABLE ia_alertas.regla_negocio_ia (
    id_regla INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descuento_maximo DECIMAL(5,2),
    activar_promociones BOOLEAN DEFAULT TRUE,
    activo BOOLEAN DEFAULT TRUE
);

-- ==============================================================================
-- FASE 2: INSERTAR DATOS INICIALES EN CATALOGOS
-- ==============================================================================

-- Estados generales
INSERT INTO catalogos.cat_estado_general (nombre, activo)
VALUES
    ('ACTIVO', TRUE),
    ('INACTIVO', TRUE),
    ('PENDIENTE', TRUE),
    ('APROBADO', TRUE),
    ('RECHAZADO', TRUE),
    ('EN PROCESO', TRUE),
    ('CANCELADO', TRUE)
ON CONFLICT DO NOTHING;

-- Estados de lote
INSERT INTO catalogos.cat_estado_lote (nombre, activo)
VALUES
    ('EN_ALMACEN', TRUE),
    ('EN_TRANSITO', TRUE),
    ('VENCIDO', TRUE),
    ('PROXIMO_A_VENCER', TRUE),
    ('DEVUELTO', TRUE),
    ('CONSUMIDO', TRUE),
    ('CUARENTENA', TRUE)
ON CONFLICT DO NOTHING;

-- Tipos de movimiento
INSERT INTO catalogos.cat_tipo_movimiento (nombre, naturaleza, activo)
VALUES
    ('INGRESO', 'INGRESO', TRUE),
    ('SALIDA', 'SALIDA', TRUE),
    ('TRASLADO', 'AJUSTE', TRUE),
    ('DEVOLUCION', 'INGRESO', TRUE),
    ('AJUSTE_POSITIVO', 'AJUSTE', TRUE),
    ('AJUSTE_NEGATIVO', 'AJUSTE', TRUE)
ON CONFLICT DO NOTHING;

-- Niveles de alerta
INSERT INTO catalogos.cat_nivel_alerta (nombre, activo)
VALUES
    ('CRITICO', TRUE),
    ('ALTO', TRUE),
    ('MEDIO', TRUE),
    ('BAJO', TRUE),
    ('INFORMATIVO', TRUE)
ON CONFLICT DO NOTHING;

-- Estados de aprobacion
INSERT INTO catalogos.cat_estado_aprobacion (nombre, activo)
VALUES
    ('PENDIENTE', TRUE),
    ('APROBADO', TRUE),
    ('RECHAZADO', TRUE),
    ('EN_REVISION', TRUE)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- FASE 3: INSERTAR ROLES DE BASE DE DATOS (seguridad.rol_bd)
-- ==============================================================================

INSERT INTO seguridad.rol_bd (nombre_rol_bd, descripcion, activo)
VALUES
    ('rol_admin_sacpa', 'Rol de PostgreSQL con acceso total a todos los esquemas SACPA', TRUE),
    ('rol_supervisor_sacpa', 'Rol de PostgreSQL para supervision de campo y bodegas', TRUE),
    ('rol_bodeguero_sacpa', 'Rol de PostgreSQL limitado a inventario y almacen', TRUE),
    ('rol_tecnico_sacpa', 'Rol de PostgreSQL para tecnicos de campo', TRUE),
    ('rol_proveedor_sacpa', 'Rol de PostgreSQL para portal de proveedores externalizados', TRUE),
    ('rol_gerente_sacpa', 'Rol de PostgreSQL de lectura para reportes ejecutivos', TRUE)
ON CONFLICT (nombre_rol_bd) DO NOTHING;

-- Insertar tipos de objeto de seguridad
INSERT INTO seguridad.tipo_objeto_seguridad (nombre, descripcion, activo)
VALUES
    ('TABLA', 'Tablas relacionales en los esquemas de PostgreSQL', TRUE),
    ('VISTA', 'Vistas de base de datos para reportes y lectura', TRUE),
    ('FUNCION', 'Funciones y procedimientos almacenados en la BD', TRUE),
    ('ENDPOINT_API', 'Endpoint REST del servidor Backend Spring Boot', TRUE),
    ('MODULO_UI', 'Modulo o pantalla del frontend Angular', TRUE)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- FASE 4: INSERTAR ROLES DEL SISTEMA (seguridad.rol)
-- ==============================================================================

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Administrador', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_admin_sacpa'
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Supervisor', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_supervisor_sacpa'
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Bodeguero', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_bodeguero_sacpa'
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Tecnico de Campo', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_tecnico_sacpa'
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Proveedor', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_proveedor_sacpa'
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO seguridad.rol (nombre, id_estado, id_rol_bd)
SELECT 'Gerente', 1, id_rol_bd FROM seguridad.rol_bd WHERE nombre_rol_bd = 'rol_gerente_sacpa'
ON CONFLICT (nombre) DO NOTHING;

-- ==============================================================================
-- FASE 5: INSERTAR PRIVILEGIOS BASE (seguridad.privilegio)
-- ==============================================================================

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto)
SELECT 'Gestion de Usuarios', 'ALL', TRUE, id_tipo_objeto FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto)
SELECT 'Gestion de Roles y Permisos', 'ALL', TRUE, id_tipo_objeto FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto)
SELECT 'Gestion de Temporadas Agricolas', 'ALL', TRUE, id_tipo_objeto FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto)
SELECT 'Aprobacion de Sugerencias IA y Promociones', 'ALL', TRUE, id_tipo_objeto FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
ON CONFLICT DO NOTHING;

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto)
SELECT 'Control de Inventario y Bodegas', 'SELECT, INSERT, UPDATE', TRUE, id_tipo_objeto FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
ON CONFLICT DO NOTHING;

-- Privilegios granulares por esquema/tabla
INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Lectura de Productos', 'SELECT', TRUE, id_tipo_objeto, 'inventario', 'producto' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'inventario' AND nombre_tabla = 'producto' AND accion = 'SELECT');

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Creacion de Productos', 'INSERT', TRUE, id_tipo_objeto, 'inventario', 'producto' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'inventario' AND nombre_tabla = 'producto' AND accion = 'INSERT');

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Edicion de Productos', 'UPDATE', TRUE, id_tipo_objeto, 'inventario', 'producto' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'inventario' AND nombre_tabla = 'producto' AND accion = 'UPDATE');

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Eliminacion de Productos', 'DELETE', TRUE, id_tipo_objeto, 'inventario', 'producto' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'inventario' AND nombre_tabla = 'producto' AND accion = 'DELETE');

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Lectura de Catalogos de Estado', 'SELECT', TRUE, id_tipo_objeto, 'catalogos', 'cat_estado_general' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'catalogos' AND nombre_tabla = 'cat_estado_general' AND accion = 'SELECT');

INSERT INTO seguridad.privilegio (nombre, accion, activo, id_tipo_objeto, esquema, nombre_tabla)
SELECT 'Lectura de Auditorias', 'SELECT', TRUE, id_tipo_objeto, 'seguridad', 'auditoria' FROM seguridad.tipo_objeto_seguridad WHERE nombre = 'TABLA' LIMIT 1
WHERE NOT EXISTS (SELECT 1 FROM seguridad.privilegio WHERE esquema = 'seguridad' AND nombre_tabla = 'auditoria' AND accion = 'SELECT');

-- ==============================================================================
-- FASE 6: INSERTAR REGLA DE NEGOCIO IA Y MODELO BASE
-- ==============================================================================

INSERT INTO ia_alertas.regla_negocio_ia (descuento_maximo, activar_promociones, activo)
VALUES (35.00, TRUE, TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO ia_alertas.modelo_ia (nombre_modelo, version, descripcion, activo)
VALUES ('AgroSense Predictor de Caducidad', 'v2.4-PROD', 'Modelo de IA para estimar fechas de caducidad y sugerir descuentos automaticos en lotes.', TRUE)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- FASE 7: CREACION DE ROLES DE GRUPO (NOLOGIN - Hardening)
-- ==============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_administrador') THEN
        CREATE ROLE grupo_administrador NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_bodeguero') THEN
        CREATE ROLE grupo_bodeguero NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_supervisor') THEN
        CREATE ROLE grupo_supervisor NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_tecnico_campo') THEN
        CREATE ROLE grupo_tecnico_campo NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_proveedor') THEN
        CREATE ROLE grupo_proveedor NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'grupo_gerente') THEN
        CREATE ROLE grupo_gerente NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT;
    END IF;
END
$$;

COMMENT ON ROLE grupo_administrador IS 'Acceso total DDL y DML sobre todos los esquemas agricolas.';
COMMENT ON ROLE grupo_bodeguero IS 'Gestion fisica y operativa de inventarios y almacenes.';
COMMENT ON ROLE grupo_supervisor IS 'Autorizaciones y supervision de alertas analiticas por IA.';
COMMENT ON ROLE grupo_tecnico_campo IS 'Registro de aplicaciones en parcelas y consulta de insumos.';
COMMENT ON ROLE grupo_proveedor IS 'Insercion externa de lotes y cargas documentales de control.';
COMMENT ON ROLE grupo_gerente IS 'Consultas gerenciales, reportes y dashboards ejecutivos.';

-- ==============================================================================
-- FASE 8: POLITICAS DE AISLAMIENTO (Hardening de Esquemas)
-- ==============================================================================

REVOKE ALL ON SCHEMA seguridad, catalogos, geografia, entidades, inventario, operaciones, ia_alertas, gerencia FROM PUBLIC;

GRANT USAGE ON SCHEMA seguridad, catalogos, geografia, entidades, inventario, operaciones, ia_alertas, gerencia TO grupo_administrador;
GRANT USAGE ON SCHEMA inventario, operaciones, catalogos, ia_alertas, entidades TO grupo_bodeguero;
GRANT USAGE ON SCHEMA inventario, operaciones, ia_alertas, catalogos TO grupo_supervisor;
GRANT USAGE ON SCHEMA inventario, operaciones TO grupo_tecnico_campo;
GRANT USAGE ON SCHEMA inventario, ia_alertas TO grupo_proveedor;
GRANT USAGE ON SCHEMA gerencia, catalogos, inventario, operaciones, ia_alertas TO grupo_gerente;

-- ==============================================================================
-- FASE 9: ASIGNACION GRANULAR DE PRIVILEGIOS (DML)
-- ==============================================================================

-- 9.1 Permisos del Administrador (acceso total)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA seguridad, catalogos, geografia, entidades, inventario, operaciones, ia_alertas, gerencia TO grupo_administrador;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA seguridad, catalogos, geografia, entidades, inventario, operaciones, ia_alertas, gerencia TO grupo_administrador;

-- 9.2 Permisos del Bodeguero
GRANT SELECT, INSERT, UPDATE ON inventario.lotes, inventario.documentos_lote, inventario.historial_estado_lote, inventario.producto, inventario.categoria TO grupo_bodeguero;
GRANT SELECT, INSERT ON operaciones.movimientos_inventario TO grupo_bodeguero;
GRANT SELECT ON catalogos.cat_estado_general, catalogos.cat_estado_lote, catalogos.cat_tipo_movimiento TO grupo_bodeguero;
GRANT SELECT ON entidades.proveedor TO grupo_bodeguero;
GRANT SELECT ON ia_alertas.alertas_caducidad, ia_alertas.notificacion TO grupo_bodeguero;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA inventario, operaciones TO grupo_bodeguero;

-- 9.3 Permisos del Supervisor
GRANT SELECT ON inventario.lotes, inventario.producto, inventario.almacen, inventario.zona_almacen, inventario.estanteria, inventario.ubicacion_interna TO grupo_supervisor;
GRANT SELECT ON operaciones.movimientos_inventario, operaciones.devoluciones, operaciones.uso_campo TO grupo_supervisor;
GRANT UPDATE (id_estado_aprobacion) ON operaciones.movimientos_inventario TO grupo_supervisor;
GRANT UPDATE (id_estado_aprobacion) ON ia_alertas.sugerencias_ia TO grupo_supervisor;
GRANT SELECT, INSERT, UPDATE ON ia_alertas.promociones, ia_alertas.promocion_detalle TO grupo_supervisor;
GRANT SELECT, INSERT, UPDATE ON operaciones.devoluciones TO grupo_supervisor;
GRANT SELECT ON catalogos.* TO grupo_supervisor;
GRANT SELECT ON ia_alertas.alertas_caducidad, ia_alertas.notificacion, ia_alertas.temporadas_agricolas TO grupo_supervisor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA operaciones, ia_alertas TO grupo_supervisor;

-- 9.4 Permisos del Tecnico de Campo
GRANT SELECT ON inventario.lotes, inventario.producto, inventario.documentos_lote TO grupo_tecnico_campo;
GRANT SELECT, INSERT ON operaciones.uso_campo TO grupo_tecnico_campo;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA operaciones TO grupo_tecnico_campo;

-- 9.5 Permisos del Proveedor
GRANT INSERT, SELECT ON inventario.lotes, inventario.documentos_lote TO grupo_proveedor;
GRANT SELECT ON ia_alertas.notificacion TO grupo_proveedor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA inventario TO grupo_proveedor;

-- 9.6 Permisos del Gerente (reportes y consultas gerenciales)
GRANT SELECT ON ALL TABLES IN SCHEMA gerencia TO grupo_gerente;
GRANT SELECT ON inventario.lotes, inventario.producto, inventario.categoria, inventario.almacen TO grupo_gerente;
GRANT SELECT ON operaciones.movimientos_inventario, operaciones.devoluciones TO grupo_gerente;
GRANT SELECT ON ia_alertas.alertas_caducidad, ia_alertas.sugerencias_ia, ia_alertas.promociones, ia_alertas.temporadas_agricolas TO grupo_gerente;
GRANT SELECT ON catalogos.* TO grupo_gerente;

-- ==============================================================================
-- FASE 10: CREACION DE USUARIOS DE CONEXION (LOGIN)
-- ==============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'administrador_agro') THEN
        CREATE USER administrador_agro WITH ENCRYPTED PASSWORD 'admin123' CONNECTION LIMIT -1;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'supervisor_agro') THEN
        CREATE USER supervisor_agro WITH ENCRYPTED PASSWORD 'super123' CONNECTION LIMIT -1;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'tecnico_campo_agro') THEN
        CREATE USER tecnico_campo_agro WITH ENCRYPTED PASSWORD 'tecnico123' CONNECTION LIMIT -1;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'proveedor_agro') THEN
        CREATE USER proveedor_agro WITH ENCRYPTED PASSWORD 'proveedor123' CONNECTION LIMIT -1;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'bodeguero_agro') THEN
        CREATE USER bodeguero_agro WITH ENCRYPTED PASSWORD 'bodeguero123' CONNECTION LIMIT -1;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'gerente_agro') THEN
        CREATE USER gerente_agro WITH ENCRYPTED PASSWORD 'gerente123' CONNECTION LIMIT -1;
    END IF;
END
$$;

-- ==============================================================================
-- FASE 11: ASIGNACION DE ROLES A USUARIOS
-- ==============================================================================

GRANT grupo_administrador TO administrador_agro;
GRANT grupo_supervisor TO supervisor_agro;
GRANT grupo_tecnico_campo TO tecnico_campo_agro;
GRANT grupo_proveedor TO proveedor_agro;
GRANT grupo_bodeguero TO bodeguero_agro;
GRANT grupo_gerente TO gerente_agro;

-- ==============================================================================
-- FASE 12: CREAR USUARIO APLICACION (para Spring Boot)
-- ==============================================================================

DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_sacpa') THEN
        CREATE USER app_sacpa WITH ENCRYPTED PASSWORD 'AppSacpa2024.' CONNECTION LIMIT -1;
    END IF;
END
$$;

GRANT grupo_administrador TO app_sacpa;

-- ==============================================================================
-- VERIFICACION FINAL
-- ==============================================================================

SELECT 'SCRIPT SACPA EJECUTADO CORRECTAMENTE' AS resultado;
SELECT COUNT(*) AS total_esquemas FROM information_schema.schemata WHERE schema_name IN ('catalogos','geografia','entidades','seguridad','inventario','operaciones','ia_alertas','gerencia');
SELECT COUNT(*) AS total_tablas FROM information_schema.tables WHERE table_schema IN ('catalogos','geografia','entidades','seguridad','inventario','operaciones','ia_alertas','gerencia');
SELECT COUNT(*) AS total_roles FROM seguridad.rol;
SELECT COUNT(*) AS total_privilegios FROM seguridad.privilegio;
SELECT COUNT(*) AS total_catalogos_estado FROM catalogos.cat_estado_general;

-- ==============================================================================
-- FIN DEL SCRIPT MAESTRO SACPA
-- ==============================================================================
