-- ==============================================================================
-- SCRIPT MÓDULO 3 — Plagas y Cultivos (Motor de Sugerencias por diagnóstico)
-- ------------------------------------------------------------------------------
-- El Técnico ya no elige una categoría genérica ("Herbicidas"): selecciona el
-- CULTIVO del cliente y la PLAGA que lo afecta, y el motor de sugerencias filtra
-- los productos etiquetados para ese diagnóstico (en vez de por categoría).
--
-- Nuevo:
--   catalogos.cat_plaga             catálogo de plagas/enfermedades
--   catalogos.cat_cultivo           catálogo de cultivos
--   inventario.producto.instrucciones_aplicacion   dosis/modo de uso (va en la factura)
--   inventario.producto_plaga       qué plagas trata cada producto (N:M)
--   inventario.producto_cultivo     en qué cultivos aplica cada producto (N:M)
-- ==============================================================================

CREATE TABLE catalogos.cat_plaga (
    id_plaga  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre    VARCHAR(150) NOT NULL UNIQUE,
    id_estado INTEGER REFERENCES catalogos.cat_estado_general(id_estado)
);

CREATE TABLE catalogos.cat_cultivo (
    id_cultivo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR(150) NOT NULL UNIQUE,
    id_estado  INTEGER REFERENCES catalogos.cat_estado_general(id_estado)
);

ALTER TABLE inventario.producto ADD COLUMN IF NOT EXISTS instrucciones_aplicacion TEXT;

CREATE TABLE inventario.producto_plaga (
    id_producto INTEGER NOT NULL REFERENCES inventario.producto(id_producto),
    id_plaga    INTEGER NOT NULL REFERENCES catalogos.cat_plaga(id_plaga),
    PRIMARY KEY (id_producto, id_plaga)
);

CREATE TABLE inventario.producto_cultivo (
    id_producto INTEGER NOT NULL REFERENCES inventario.producto(id_producto),
    id_cultivo  INTEGER NOT NULL REFERENCES catalogos.cat_cultivo(id_cultivo),
    PRIMARY KEY (id_producto, id_cultivo)
);

-- ==============================================================================
-- Datos semilla — catálogo de cultivos y plagas
-- ==============================================================================
INSERT INTO catalogos.cat_cultivo (nombre, id_estado) VALUES
    ('Cacao', 1), ('Café', 1), ('Banano', 1), ('Maíz', 1), ('Arroz', 1)
ON CONFLICT DO NOTHING;

INSERT INTO catalogos.cat_plaga (nombre, id_estado) VALUES
    ('Monilia', 1),
    ('Escoba de Bruja', 1),
    ('Roya del Café', 1),
    ('Broca del Café', 1),
    ('Sigatoka Negra', 1),
    ('Cogollero', 1)
ON CONFLICT DO NOTHING;

-- ==============================================================================
-- Instrucciones de aplicación + etiquetado de productos existentes
-- (para poder probar el flujo cultivo→plaga→combo de inmediato)
-- ==============================================================================
UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 20ml por bomba de 20L y aplicar en follaje cada 15 días. No aplicar en floración.'
    WHERE id_producto = 3;  -- Mancozeb 80 WP (Fungicida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 15g por litro de agua y aplicar cada 20 días, cubriendo tronco y ramas afectadas.'
    WHERE id_producto = 13; -- Cobre Pentahidratado (Fungicida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 10ml por bomba de 20L y aplicar preventivamente cada 21 días en época lluviosa.'
    WHERE id_producto = 18; -- Azoxistrobina 25 SC (Fungicida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 25ml por bomba de 20L y aplicar sobre el follaje cada 14 días.'
    WHERE id_producto = 8;  -- Clorotalonil 720 SC (Fungicida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 5ml por litro de agua y aplicar dirigido a hojas y frutos cada 10 días.'
    WHERE id_producto = 19; -- Spinosad (Insecticida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 8ml por bomba de 20L y aplicar al detectar los primeros daños en cogollo.'
    WHERE id_producto = 14; -- Abamectina 1.8 EC (Insecticida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 30ml por bomba de 20L y aplicar dirigido al cogollo en horas de la tarde.'
    WHERE id_producto = 9;  -- Cipermetrina 25 EC (Insecticida)

UPDATE inventario.producto SET instrucciones_aplicacion =
    'Diluir 15ml por bomba de 20L y aplicar al follaje cada 12 días.'
    WHERE id_producto = 4;  -- Imidacloprid 350 SC (Insecticida)

-- Etiquetado producto ↔ cultivo
INSERT INTO inventario.producto_cultivo (id_producto, id_cultivo)
SELECT p.id_producto, c.id_cultivo FROM (VALUES
    (3, 'Cacao'), (13, 'Cacao'),
    (18, 'Café'), (19, 'Café'), (14, 'Café'),
    (8, 'Banano'),
    (9, 'Maíz'), (4, 'Maíz')
) AS x(id_producto, cultivo)
JOIN inventario.producto p ON p.id_producto = x.id_producto
JOIN catalogos.cat_cultivo c ON c.nombre = x.cultivo
ON CONFLICT DO NOTHING;

-- Etiquetado producto ↔ plaga
INSERT INTO inventario.producto_plaga (id_producto, id_plaga)
SELECT p.id_producto, pl.id_plaga FROM (VALUES
    (3, 'Monilia'),
    (13, 'Escoba de Bruja'),
    (18, 'Roya del Café'),
    (19, 'Broca del Café'), (14, 'Broca del Café'),
    (8, 'Sigatoka Negra'),
    (9, 'Cogollero'), (4, 'Cogollero')
) AS x(id_producto, plaga)
JOIN inventario.producto p ON p.id_producto = x.id_producto
JOIN catalogos.cat_plaga pl ON pl.nombre = x.plaga
ON CONFLICT DO NOTHING;
