-- Hueco mas grave detectado contra el checklist oficial de AGROCALIDAD
-- (Resolucion 0227, Anexo 1, punto 25): "archivo de recetas firmadas por un
-- Ing. Agronomo o Ing. Agropecuario para el expendio de productos plaguicidas
-- con categoria toxicologica Ia y Ib, y plaguicidas de venta restringida...
-- El archivo debera permanecer durante dos anos en el almacen de expendio."
--
-- Antes de esto, VentaCreateRequestDTO/DetalleVentaRequestDTO no tenian
-- ningun campo de receta: un tecnico podia vender un litro de un plaguicida
-- Ia con la misma facilidad que un fertilizante organico.

CREATE TABLE operaciones.receta_agricola (
    id_receta               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_autorizacion     VARCHAR(100) NOT NULL,
    id_cliente              INTEGER NOT NULL REFERENCES entidades.clientes(id_cliente),
    id_producto             INTEGER NOT NULL REFERENCES inventario.producto(id_producto),
    nombre_profesional      VARCHAR(200) NOT NULL,
    registro_profesional    VARCHAR(100),
    documento_url           TEXT,
    fecha_emision           DATE NOT NULL,
    id_usuario_registro     INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario),
    fecha_registro          TIMESTAMP NOT NULL DEFAULT now(),
    usada                   BOOLEAN NOT NULL DEFAULT false,
    id_venta_uso            INTEGER REFERENCES operaciones.ventas(id),
    fecha_uso               TIMESTAMP,
    CONSTRAINT ck_receta_fecha_emision CHECK (fecha_emision <= CURRENT_DATE)
);

-- Una misma receta no puede pagar dos veces la vida (evita reutilizarla en
-- dos ventas creadas casi al mismo tiempo, condicion de carrera aparte,
-- pero al menos la reutilizacion "tranquila" queda bloqueada a nivel de fila).
CREATE UNIQUE INDEX uk_receta_uso_unico ON operaciones.receta_agricola (id_receta) WHERE usada = true;

CREATE INDEX ix_receta_agricola_cliente_producto ON operaciones.receta_agricola (id_cliente, id_producto) WHERE usada = false;

COMMENT ON TABLE operaciones.receta_agricola IS
    'Recetas agricolas para la venta de plaguicidas Ia/Ib o de venta restringida. Conservar 2 anos segun Resolucion 0227 Anexo 1 punto 25 -- no purgar automaticamente.';
