-- Checklist AGROCALIDAD (Resolucion 0227, Anexo 1, punto 20): "registro de control de
-- temperatura y humedad del area de almacenamiento, para conservar la integridad e
-- inocuidad de los plaguicidas". El sistema ya modela zona_almacen.condicion_climatica
-- como texto libre, pero no habia forma de REGISTRAR lecturas periodicas ni un rango
-- aceptable contra el cual compararlas.

ALTER TABLE inventario.zona_almacen
    ADD COLUMN temperatura_minima NUMERIC(5,2),
    ADD COLUMN temperatura_maxima NUMERIC(5,2);

CREATE TABLE inventario.registro_temperatura (
    id_registro         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_zona             INTEGER NOT NULL REFERENCES inventario.zona_almacen(id_zona),
    temperatura         NUMERIC(5,2) NOT NULL,
    humedad_relativa    NUMERIC(5,2),
    fuera_de_rango      BOOLEAN NOT NULL DEFAULT false,
    observaciones       VARCHAR(300),
    id_usuario_registro INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario),
    fecha_hora          TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX ix_registro_temperatura_zona_fecha ON inventario.registro_temperatura (id_zona, fecha_hora DESC);

COMMENT ON TABLE inventario.registro_temperatura IS
    'Bitacora de control de temperatura/humedad por zona de bodega (Resolucion 0227, Anexo 1 punto 20).';
