-- Checklist AGROCALIDAD (Resolucion 0227, Anexo 1, puntos 1-2): el almacen debe tener
-- disponible para inspeccion su documentacion institucional -- Permiso de Funcionamiento
-- AGROCALIDAD, LUAE (licencia unica de actividades economicas del municipio), RUC,
-- Certificado Ambiental, Registro Sanitario del establecimiento, etc. El sistema ya
-- archivaba documentos POR LOTE (documentos_lote), pero no existia ningun lugar para
-- guardar los documentos del establecimiento en si.

CREATE TABLE inventario.documento_institucional (
    id_documento         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_almacen           INTEGER REFERENCES inventario.almacen(id_almacen),
    tipo_documento       VARCHAR(100) NOT NULL,
    nombre_archivo       VARCHAR(200) NOT NULL,
    ruta_archivo         VARCHAR(500) NOT NULL,
    fecha_emision        DATE,
    fecha_vencimiento    DATE,
    id_usuario_subida    INTEGER NOT NULL REFERENCES seguridad.usuario(id_usuario),
    fecha_subida         TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX ix_documento_institucional_almacen ON inventario.documento_institucional (id_almacen);

COMMENT ON TABLE inventario.documento_institucional IS
    'Documentos institucionales del establecimiento (permiso AGROCALIDAD, LUAE, RUC, certificado ambiental, registro sanitario) -- id_almacen NULL = documento de la empresa en general, no de una bodega puntual.';
